In [2]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
arr[::-1]

array([5, 4, 6, 3, 2, 1])

In [8]:
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
arr.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1==arr2)

[[ True  True]
 [ True  True]]


In [42]:
#unique, argmax, where
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts = True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(x == most_frequent_value)
most_frequent_value, indices


(1, (array([0, 5, 7, 8, 9], dtype=int64),))

In [43]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts = True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(y == most_frequent_value)
most_frequent_value, indices

(1, (array([0, 1, 2], dtype=int64),))

In [54]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg, 1))
print(np.sum(gfg, 0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [65]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diagonals = np.diagonal(n_array)
print(np.sum(diagonals))
print(np.linalg.eig(n_array))
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

176
(array([98.16835147, 28.097044  , 49.73460452]), array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [75]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(np.dot(p, q)) # p@q also works
np.cov(p, q)

[[16 19]
 [26 31]]


array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [80]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print(p@q)
p = p.flatten()
q = q.flatten()
print(np.cov(p, q))

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [85]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x, y))
print(np.outer(x, y))
X, Y = np.meshgrid(x.flatten(), y.flatten())
cartesian = np.vstack([X.ravel(), Y.ravel()]).T

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [102]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print(abs(array))

print(np.percentile(array.flatten(), [25, 50, 75]))
print(np.percentile(array, [25, 50, 75], axis = 1))
print(np.percentile(array, [25, 50, 75], axis = 0))

print(np.mean(array.flatten()))
print(np.median(array.flatten()))
print(np.std(array.flatten()))

print(np.mean(array, axis = 1))
print(np.mean(array, axis = 0))

print(np.median(array, axis = 1))
print(np.median(array, axis = 0))

print(np.std(array, axis = 1))
print(np.std(array, axis = 0))

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
-0.5
-0.5
3.8622100754188224
[ 0.66666667 -1.66666667]
[-1.5  1.5 -1.5]
[ 1. -4.]
[-1.5  1.5 -1.5]
[2.05480467 4.78423336]
[2.5 3.5 4.5]


In [105]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [118]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print(np.sort(array))
print(np.argsort(array))
print(sorted_array[0:4])
print(sorted_array[-5:])


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [16]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(array[array%1 == 0])
print(array[array%1 != 0])

[1. 2. 3. 2.]
[1.2 2.2]


In [6]:
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)

    if len(img_array.shape) == 3:
        print("Image is RGB")
        np.savetxt("img_rgb.txt", img_array.reshape(-1, img_array.shape[-1]), fmt = "%d")
    elif len(img_array.shape) == 2:
        print("Image is Greyscale")
        np.savetxt("img_greyscale.txt", img_array, fmt = "%d")
    else:
        raise ValueError("Unsupported image format")
    print("Image saved successfully")
        

In [ ]:
greyscale_array = np.loadtxt("img_greyscale.txt", dtype = np.uint8) 
rgb_array = np.loadtxt("img_rgb.txt", dtype = np.uint8)